# -*- coding: utf-8 -*-
"""04_bert_train.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1njdFEBxEuuItcTkDGY6k8U_Ios8-6RxE
"""

from google.colab import drive
drive.mount('/content/drive')

# Cell 1: Install & imports (run once per Colab session)

!pip install -q transformers datasets accelerate evaluate

import os
import random
import numpy as np
import pandas as pd

import torch
from transformers import (
    AutoTokenizer,
    AutoModelForSequenceClassification,
)

# For later phases (training/eval), but okay to import now
from sklearn.metrics import (
    accuracy_score,
    precision_recall_fscore_support,
    roc_auc_score,
    average_precision_score,
    confusion_matrix,
    roc_curve,
    precision_recall_curve,
)

# ---- Paths aligned with Milestone 2 ----
PROJECT_ROOT = "/content/drive/MyDrive/EDA_Project"
DATA_ROOT    = os.path.join(PROJECT_ROOT, "size_data_f1")

os.makedirs(PROJECT_ROOT, exist_ok=True)

print("PROJECT_ROOT:", PROJECT_ROOT)
print("DATA_ROOT   :", DATA_ROOT)

# ---- Global config ----
DATASET_NAME = "sst2"

SIZE_SPLITS = ["1_tiny", "2_small", "3_standard", "4_full"]
TEST_PATH   = os.path.join(DATA_ROOT, "test", DATASET_NAME, "test.txt")

# Check that test file exists
print("Test file exists? ", os.path.exists(TEST_PATH), TEST_PATH)

# ---- Reproducibility ----
SEED = 42

def set_global_seed(seed=42):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)
    # deterministic behavior (may slow down a bit)
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False

set_global_seed(SEED)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Using device:", device)

# 🔧 Cell 2: Best EDA config per size (fill from Milestone 2 results)

# TODO: update these according to your actual metrics from 02_train.ipynb
# Example only (you MUST adjust based on your summary_all_runs / best_per_size tables)
BEST_EDA_PER_SIZE = {
    "1_tiny":     {"method": "sr", "alpha": 0.1},   # e.g., synonym replacement, alpha=0.1
    "2_small":    {"method": "ri", "alpha": 0.3},   # e.g., random insertion, alpha=0.3
    "3_standard": {"method": "sr", "alpha": 0.1},
    "4_full":     {"method": "sr", "alpha": 0.1},
}

# Helper to build the path to the selected EDA file for a given size
def get_eda_train_path(size, dataset=DATASET_NAME):
    cfg = BEST_EDA_PER_SIZE.get(size)
    if cfg is None:
        raise ValueError(f"No EDA config set for size={size}")
    method = cfg["method"]
    alpha  = cfg["alpha"]
    folder = os.path.join(DATA_ROOT, size, dataset)
    return os.path.join(folder, f"train_{method}_{alpha}.txt")

# Helper to get baseline (non-EDA) train path
def get_baseline_train_path(size, dataset=DATASET_NAME):
    folder = os.path.join(DATA_ROOT, size, dataset)
    return os.path.join(folder, "train_orig.txt")

# Quick sanity check: paths
for size in SIZE_SPLITS:
    base_path = get_baseline_train_path(size)
    eda_path  = get_eda_train_path(size)
    print(f"\n=== {size} ===")
    print("Baseline train:", base_path, "exists?", os.path.exists(base_path))
    print("EDA train     :", eda_path,  "exists?", os.path.exists(eda_path))

# 🔧 Cell 3: Utility to load SST-2 style txt files into a DataFrame

def load_sst2_txt(path):
    """
    Reads a SST-2 style file: <label>\t<sentence>\n
    Returns a DataFrame with columns: ['label', 'text'].
    """
    if not os.path.exists(path):
        raise FileNotFoundError(f"File not found: {path}")

    labels = []
    texts  = []
    with open(path, "r", encoding="utf-8") as f:
        for line in f:
            line = line.rstrip("\n")
            if not line:
                continue
            parts = line.split("\t", 1)
            if len(parts) != 2:
                # Skip malformed lines but log them
                # (You can also assert here depending on your data quality)
                # print("Skipping malformed line:", line)
                continue
            label_str, text = parts
            try:
                label = int(label_str)
            except ValueError:
                # If label isn't an int for some reason, skip
                # print("Skipping line with non-int label:", line)
                continue
            labels.append(label)
            texts.append(text)

    df = pd.DataFrame({"label": labels, "text": texts})
    return df

# Quick smoke test on tiny baseline + test
tiny_train_df = load_sst2_txt(get_baseline_train_path("1_tiny"))
test_df       = load_sst2_txt(TEST_PATH)

print("tiny_train_df shape:", tiny_train_df.shape)
print("test_df shape:", test_df.shape)
display(tiny_train_df.head())
display(test_df.head())

# 🔧 Cell 4: Initialize BERT tokenizer (we'll reuse this later)

BERT_CHECKPOINT = "bert-base-uncased"  # or "distilbert-base-uncased" if you want lighter

tokenizer = AutoTokenizer.from_pretrained(BERT_CHECKPOINT)

MAX_SEQ_LEN = 50   # to match your previous 50-token limit

print("Loaded tokenizer:", BERT_CHECKPOINT)
print("Max seq length:", MAX_SEQ_LEN)

# 🔹 Cell 5: Convert DataFrame to tokenized PyTorch-ready datasets

from datasets import Dataset
from torch.utils.data import DataLoader

def df_to_hf_dataset(df: pd.DataFrame):
    """
    Convert a DataFrame with columns ['text', 'label'] into a HF Dataset.
    """
    return Dataset.from_pandas(df, preserve_index=False)

def tokenize_function(batch):
    return tokenizer(
        batch["text"],
        truncation=True,
        padding="max_length",
        max_length=MAX_SEQ_LEN,
    )

def prepare_bert_datasets(size: str, variant: str):
    """
    size: one of SIZE_SPLITS (e.g., '1_tiny')
    variant: 'baseline' or 'eda'

    Returns:
        train_dataset, test_dataset  (HF Datasets with torch format)
        meta_info (dict with paths + method/alpha if EDA)
    """
    assert size in SIZE_SPLITS, f"Unknown size: {size}"
    assert variant in ("baseline", "eda"), f"Unknown variant: {variant}"

    if variant == "baseline":
        train_path = get_baseline_train_path(size)
        method = None
        alpha  = None
    else:
        train_path = get_eda_train_path(size)
        cfg = BEST_EDA_PER_SIZE[size]
        method = cfg["method"]
        alpha  = cfg["alpha"]

    # load into DataFrames
    train_df = load_sst2_txt(train_path)
    test_df  = load_sst2_txt(TEST_PATH)

    print(f"[prepare_bert_datasets] size={size}, variant={variant}")
    print("  train_path:", train_path, " ->", train_df.shape)
    print("  test_path :", TEST_PATH,   " ->", test_df.shape)

    # HF Datasets
    ds_train = df_to_hf_dataset(train_df)
    ds_test  = df_to_hf_dataset(test_df)

    # tokenize
    ds_train = ds_train.map(tokenize_function, batched=True)
    ds_test  = ds_test.map(tokenize_function, batched=True)

    # keep only needed columns
    ds_train.set_format(
        type="torch",
        columns=["input_ids", "attention_mask", "label"],
    )
    ds_test.set_format(
        type="torch",
        columns=["input_ids", "attention_mask", "label"],
    )

    meta_info = {
        "size": size,
        "variant": variant,
        "train_path": train_path,
        "test_path": TEST_PATH,
        "method": method,
        "alpha": alpha,
    }

    return ds_train, ds_test, meta_info

# 🔹 Cell 6: Metric helpers for binary classification

def compute_metrics_full(y_true, y_prob_pos):
    """
    y_true: 1D array of ints (0/1)
    y_prob_pos: 1D array of probabilities for the positive class
    """
    y_true = np.asarray(y_true)
    y_prob_pos = np.asarray(y_prob_pos)
    y_pred = (y_prob_pos >= 0.5).astype(int)

    acc = accuracy_score(y_true, y_pred)
    precision, recall, f1, _ = precision_recall_fscore_support(
        y_true, y_pred, average="binary", zero_division=0
    )

    # AUROC / PR-AUC (handle edge cases)
    try:
        auroc = roc_auc_score(y_true, y_prob_pos)
    except Exception:
        auroc = float("nan")

    try:
        pr_auc = average_precision_score(y_true, y_prob_pos)
    except Exception:
        pr_auc = float("nan")

    cm = confusion_matrix(y_true, y_pred)

    # curves
    try:
        fpr, tpr, _ = roc_curve(y_true, y_prob_pos)
    except Exception:
        fpr, tpr = np.array([]), np.array([])

    try:
        prec_curve, rec_curve, _ = precision_recall_curve(y_true, y_prob_pos)
    except Exception:
        prec_curve, rec_curve = np.array([]), np.array([])

    metrics = {
        "acc": float(acc),
        "precision": float(precision),
        "recall": float(recall),
        "f1": float(f1),
        "auroc": None if np.isnan(auroc) else float(auroc),
        "pr_auc": None if np.isnan(pr_auc) else float(pr_auc),
    }

    curves = {
        "roc_fpr": fpr.tolist(),
        "roc_tpr": tpr.tolist(),
        "pr_precision": prec_curve.tolist(),
        "pr_recall": rec_curve.tolist(),
    }

    return metrics, cm, curves

# 🔹 Cell 7: Evaluate a BERT model on a PyTorch DataLoader

def evaluate_bert_model(model, dataloader, device):
    model.eval()
    all_probs = []
    all_labels = []

    with torch.no_grad():
        for batch in dataloader:
            input_ids = batch["input_ids"].to(device)
            attention_mask = batch["attention_mask"].to(device)
            labels = batch["label"].cpu().numpy()

            outputs = model(input_ids=input_ids, attention_mask=attention_mask)
            logits = outputs.logits.detach().cpu().numpy()
            probs = torch.softmax(torch.tensor(logits), dim=1).numpy()

            all_probs.append(probs)
            all_labels.append(labels)

    all_probs = np.concatenate(all_probs, axis=0)      # (N, 2)
    all_labels = np.concatenate(all_labels, axis=0)    # (N,)

    # probability of positive class = column 1
    y_prob_pos = all_probs[:, 1]
    metrics, cm, curves = compute_metrics_full(all_labels, y_prob_pos)
    return metrics, cm, curves

# 🔹 Cell 8: Train & evaluate BERT for one (size, variant) pair

import json
from datetime import datetime

BERT_MODELS_DIR = os.path.join(PROJECT_ROOT, "bert_models")
os.makedirs(BERT_MODELS_DIR, exist_ok=True)

def now_str():
    return datetime.now().strftime("%Y-%m-%d_%H-%M-%S")

def train_bert_run(
    size: str,
    variant: str = "baseline",        # 'baseline' or 'eda'
    num_epochs: int = 3,
    batch_size: int = 16,
    learning_rate: float = 2e-5,
    weight_decay: float = 0.0,
):
    """
    Train BERT on a given size & variant ('baseline' / 'eda').

    Returns:
        meta_path (str), model_dir (str)
    """
    # Prepare data
    ds_train, ds_test, ds_meta = prepare_bert_datasets(size, variant)

    train_loader = DataLoader(ds_train, batch_size=batch_size, shuffle=True)
    test_loader  = DataLoader(ds_test,  batch_size=batch_size, shuffle=False)

    # Model
    model = AutoModelForSequenceClassification.from_pretrained(
        BERT_CHECKPOINT,
        num_labels=2,
    )
    model.to(device)

    # Optimizer
    optimizer = torch.optim.AdamW(model.parameters(), lr=learning_rate, weight_decay=weight_decay)

    total_steps = num_epochs * len(train_loader)
    print(f"[train_bert_run] size={size}, variant={variant}, epochs={num_epochs}, steps={total_steps}")

    # Training loop (simple)
    model.train()
    for epoch in range(num_epochs):
        epoch_loss = 0.0
        for batch in train_loader:
            optimizer.zero_grad()

            input_ids = batch["input_ids"].to(device)
            attention_mask = batch["attention_mask"].to(device)
            labels = batch["label"].to(device)

            outputs = model(
                input_ids=input_ids,
                attention_mask=attention_mask,
                labels=labels,
            )
            loss = outputs.loss
            loss.backward()
            optimizer.step()

            epoch_loss += loss.item()

        avg_loss = epoch_loss / max(1, len(train_loader))
        print(f"  Epoch {epoch+1}/{num_epochs} - train loss: {avg_loss:.4f}")

    # ---- Evaluation on train and test ----
    train_metrics, train_cm, train_curves = evaluate_bert_model(model, train_loader, device)
    test_metrics, test_cm, test_curves = evaluate_bert_model(model, test_loader, device)

    print("[train_bert_run] Test metrics:", test_metrics)

    # ---- Save model ----
    timestamp = now_str()
    stub = f"{DATASET_NAME}__size-{size}__bert__{variant}__{timestamp}"
    model_dir = os.path.join(BERT_MODELS_DIR, stub)
    os.makedirs(model_dir, exist_ok=True)
    model.save_pretrained(model_dir)
    tokenizer.save_pretrained(model_dir)

    # ---- Save metadata JSON ----
    meta = {
        "dataset": DATASET_NAME,
        "size": size,
        "variant": variant,         # 'baseline' / 'eda'
        "method": ds_meta["method"],
        "alpha": ds_meta["alpha"],
        "model_family": "bert",
        "model_type": "bert",
        "checkpoint": BERT_CHECKPOINT,
        "max_seq_len": MAX_SEQ_LEN,
        "epochs": num_epochs,
        "batch_size": batch_size,
        "learning_rate": learning_rate,
        "weight_decay": weight_decay,
        "train_path": ds_meta["train_path"],
        "test_path": ds_meta["test_path"],
        "timestamp": timestamp,
        "paths": {
            "model": model_dir,
        },
        "train_metrics": train_metrics,
        "test_metrics": test_metrics,
        "train_confusion_matrix": train_cm.tolist(),
        "test_confusion_matrix": test_cm.tolist(),
        "train_curves": train_curves,
        "test_curves": test_curves,
    }

    meta_path = os.path.join(BERT_MODELS_DIR, stub + ".json")
    with open(meta_path, "w") as f:
        json.dump(meta, f, indent=2)

    print("✅ Saved model to:", model_dir)
    print("✅ Saved metadata to:", meta_path)

    return meta_path, model_dir

# 🔹 Cell 9: Example runs for 1_tiny (you can adjust epochs/bs for speed)

# BERT baseline on 1_tiny
meta_base, model_base = train_bert_run(
    size="1_tiny",
    variant="baseline",
    num_epochs=3,      # maybe 3–5 for tiny
    batch_size=16,
    learning_rate=2e-5,
)

# BERT + EDA on 1_tiny
meta_eda, model_eda = train_bert_run(
    size="1_tiny",
    variant="eda",     # uses BEST_EDA_PER_SIZE["1_tiny"]
    num_epochs=3,
    batch_size=16,
    learning_rate=2e-5,
)

# 🔹 Cell 10: Loop over all sizes

for size in SIZE_SPLITS:
    print("\n==============================")
    print(">>> BERT baseline:", size)
    train_bert_run(size=size, variant="baseline", num_epochs=3, batch_size=16, learning_rate=1e-5)

    print("\n>>> BERT + EDA:", size)
    train_bert_run(size=size, variant="eda", num_epochs=3, batch_size=16, learning_rate=1e-5)

"""## Visualisations"""

# 🔹 Cell 11: Config + JSON loader for both Keras and BERT runs

import os, glob, json
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

PROJECT_ROOT = "/content/drive/MyDrive/EDA_Project"
MODELS_DIR   = os.path.join(PROJECT_ROOT, "models")       # CNN/LSTM
BERT_MODELS_DIR = os.path.join(PROJECT_ROOT, "bert_models")  # BERT
OUT_FIG      = os.path.join(PROJECT_ROOT, "figures_m3")
OUT_TAB      = os.path.join(PROJECT_ROOT, "tables_m3")

os.makedirs(OUT_FIG, exist_ok=True)
os.makedirs(OUT_TAB, exist_ok=True)

TARGET_DATASET = "sst2"
SIZE_TO_PCT = {"1_tiny":5, "2_small":20, "3_standard":50, "4_full":100}

plt.rcParams["figure.dpi"] = 150

def load_all_meta_from_dir(models_dir):
    rows = []
    for jp in glob.glob(os.path.join(models_dir, "*.json")):
        try:
            m = json.load(open(jp))
            m["meta_path"] = jp

            # unify accuracy + metrics
            if isinstance(m.get("test_metrics"), dict):
                tm = m["test_metrics"]
                m["acc"]       = tm.get("acc", np.nan)
                m["precision"] = tm.get("precision", np.nan)
                m["recall"]    = tm.get("recall", np.nan)
                m["f1"]        = tm.get("f1", np.nan)
                m["auroc"]     = tm.get("auroc", np.nan)
                m["pr_auc"]    = tm.get("pr_auc", np.nan)
            else:
                # legacy: only test_acc
                m["acc"]       = m.get("test_acc", np.nan)
                m["precision"] = np.nan
                m["recall"]    = np.nan
                m["f1"]        = np.nan
                m["auroc"]     = np.nan
                m["pr_auc"]    = np.nan

            rows.append(m)
        except Exception as e:
            print(f"[WARN] Skip bad JSON {jp}: {e}")
    return pd.DataFrame(rows)

df_keras = load_all_meta_from_dir(MODELS_DIR)
df_bert  = load_all_meta_from_dir(BERT_MODELS_DIR)

print("Loaded Keras JSONs:", len(df_keras))
print("Loaded BERT  JSONs:", len(df_bert))

# Concatenate and keep only our dataset
df_all = pd.concat([df_keras, df_bert], ignore_index=True)
df_all = df_all[df_all["dataset"] == TARGET_DATASET].copy()

# Add pct column
df_all["pct"] = df_all["size"].map(SIZE_TO_PCT)
df_all = df_all.sort_values(["model_type","pct","variant","method","alpha","timestamp"],
                            na_position="last").reset_index(drop=True)

print("Total rows for dataset", TARGET_DATASET, ":", len(df_all))
df_all.head()

# 🔹 Cell 12: BERT — best baseline vs best EDA per size

def best_per_size_for_model(df_in, model_type="bert"):
    sub = df_in[df_in["model_type"] == model_type].copy()
    out_rows = []

    for size, grp in sub.groupby("size"):
        pct = SIZE_TO_PCT.get(size, np.nan)

        base = grp[grp["variant"] == "baseline"].sort_values("acc", ascending=False)
        eda  = grp[grp["variant"] == "eda"].sort_values("acc", ascending=False)

        if base.empty or eda.empty:
            continue

        b = base.iloc[0]
        e = eda.iloc[0]

        out_rows.append({
            "size": size,
            "pct": pct,
            "baseline_acc": float(b["acc"]),
            "baseline_f1":  float(b["f1"]) if not pd.isna(b["f1"]) else np.nan,
            "eda_acc": float(e["acc"]),
            "eda_f1":  float(e["f1"]) if not pd.isna(e["f1"]) else np.nan,
            "eda_method": e.get("method", None),
            "eda_alpha":  e.get("alpha", None),
        })

    if not out_rows:
        return pd.DataFrame()

    df_out = pd.DataFrame(out_rows).sort_values("pct").reset_index(drop=True)
    return df_out

bert_best = best_per_size_for_model(df_all, model_type="bert")
bert_best

bert_best_csv = os.path.join(OUT_TAB, "m3_bert_best_per_size.csv")
bert_best.to_csv(bert_best_csv, index=False)
print("Saved:", bert_best_csv)

# 🔹 Cell 13: Accuracy vs % dataset for BERT baseline vs EDA

def plot_bert_acc_vs_pct(df_bert_best):
    if df_bert_best.empty:
        print("[WARN] No BERT entries to plot.")
        return

    x   = df_bert_best["pct"].values
    y_b = df_bert_best["baseline_acc"].values
    y_e = df_bert_best["eda_acc"].values

    plt.figure(figsize=(5,3.5))
    plt.plot(x, y_b, marker='o', linestyle='-', label='BERT Baseline')
    plt.plot(x, y_e, marker='^', linestyle='-', label='BERT + EDA')
    plt.title("SST-2 — BERT Accuracy vs % of Training Data")
    plt.xlabel("% of training data")
    plt.ylabel("Accuracy")
    plt.ylim(0.5, 1.0)
    plt.xticks(sorted(df_bert_best["pct"].unique()))
    plt.grid(True, alpha=0.3)
    plt.legend()
    plt.tight_layout()

    out_png = os.path.join(OUT_FIG, "m3_bert_acc_vs_pct.png")
    plt.savefig(out_png, dpi=180)
    plt.close()
    print("Saved figure:", out_png)

plot_bert_acc_vs_pct(bert_best)

# 🔹 Cell 14: Compare CNN vs LSTM vs BERT (baseline only) per size

def baseline_compare_across_models(df_in):
    sub = df_in[df_in["variant"] == "baseline"].copy()
    sub = sub[sub["model_type"].isin(["cnn","lstm","bert"])]

    rows = []
    for size, grp in sub.groupby("size"):
        pct = SIZE_TO_PCT.get(size, np.nan)
        entry = {"size": size, "pct": pct}
        for mt in ["cnn","lstm","bert"]:
            g_m = grp[grp["model_type"] == mt].sort_values("acc", ascending=False)
            if g_m.empty:
                entry[f"{mt}_acc"] = np.nan
            else:
                entry[f"{mt}_acc"] = float(g_m.iloc[0]["acc"])
        rows.append(entry)

    if not rows:
        return pd.DataFrame()

    df_out = pd.DataFrame(rows).sort_values("pct").reset_index(drop=True)
    return df_out

baseline_cmp = baseline_compare_across_models(df_all)
baseline_cmp

baseline_cmp_csv = os.path.join(OUT_TAB, "m3_baseline_cnn_lstm_bert.csv")
baseline_cmp.to_csv(baseline_cmp_csv, index=False)
print("Saved:", baseline_cmp_csv)

# 🔹 Cell 15: Bar/line chart for CNN vs LSTM vs BERT (baseline only)

def plot_baseline_models(baseline_df):
    if baseline_df.empty:
        print("[WARN] No baseline comparison data.")
        return

    x = baseline_df["pct"].values
    plt.figure(figsize=(6,3.5))

    if "cnn_acc" in baseline_df.columns:
        plt.plot(x, baseline_df["cnn_acc"], marker='o', linestyle='-', label="CNN")
    if "lstm_acc" in baseline_df.columns:
        plt.plot(x, baseline_df["lstm_acc"], marker='^', linestyle='-', label="LSTM")
    if "bert_acc" in baseline_df.columns:
        plt.plot(x, baseline_df["bert_acc"], marker='s', linestyle='-', label="BERT")

    plt.title("SST-2 — Baseline Models Accuracy vs % Dataset")
    plt.xlabel("% of training data")
    plt.ylabel("Accuracy")
    plt.ylim(0.5, 1.0)
    plt.xticks(sorted(baseline_df["pct"].unique()))
    plt.grid(True, alpha=0.3)
    plt.legend()
    plt.tight_layout()

    out_png = os.path.join(OUT_FIG, "m3_baseline_models_acc_vs_pct.png")
    plt.savefig(out_png, dpi=180)
    plt.close()
    print("Saved figure:", out_png)

plot_baseline_models(baseline_cmp)

# 🔹 Cell 16: Paper-style BERT table (Acc values)

def fmt_pct_acc(x):
    if pd.isna(x):
        return ""
    return f"{100*x:.1f}%"

def build_bert_paper_table(df_bert_best):
    order = [5, 20, 50, 100]
    acc_map_base = {p:a for p,a in zip(df_bert_best["pct"], df_bert_best["baseline_acc"])}
    acc_map_eda  = {p:a for p,a in zip(df_bert_best["pct"], df_bert_best["eda_acc"])}

    rows = []
    for pct in order:
        base = acc_map_base.get(pct, np.nan)
        eda  = acc_map_eda.get(pct, np.nan)
        rows.append({
            "% train": f"{pct}%",
            "BERT Baseline": fmt_pct_acc(base),
            "BERT + EDA": fmt_pct_acc(eda),
        })
    return pd.DataFrame(rows)

bert_paper_tbl = build_bert_paper_table(bert_best)
bert_paper_csv = os.path.join(OUT_TAB, "m3_bert_paper_table.csv")
bert_paper_tbl.to_csv(bert_paper_csv, index=False)
print("Saved:", bert_paper_csv)
bert_paper_tbl